### ISSUE TITLE
[Question] Will Symfony Flex support multiple kernels?

### ISSUE THREAD

**Issue by chirimoya** [symfony/flex#110]
Hi, I'm the lead developer of the Sulu CMS, a content managment system based von Symfony. 

We follow the Symfony Flex movement and looking forward to get Sulu ready as early as possible.

While evaluating the current Flex architecture we discovered one big challenge we have to tackle. Sulu differs from the Symfony Standard only in one critical point. We use a multi kernel setup. One kernel for the front-end (website) and one for the backe-end (admin). The advantage of sessionless websites and don't have to bootstrap all bundles, e.g. the security components in the front-end, are worth to have two seperate kernels. 

Do you plan to support multi kernel setups with Symfony Flex?

Do you have another idea which could solve this issue?

Many thanks!

**Comment by fabpot** [comment]
Symfony Flex is "just" a Composer plugin that "executes" recipes. So it's quite dumb and does not really care about the way you organize your code. That said, the default skeleton and the official recipes associated to it are optimized for a single kernel.

I don't have any definitive answers about the best way to manage that issue, but I suppose that having 2 applications would be the easiest path (think microservices-like architecture). Sharing common code can still be done quite easily with symlinks and the like (or proper Composer packages).

Finally, I'm not sure what supporting multi-kernel setups would look like to be honest.

**Comment by chirimoya** [comment]
Our initial idea was to add an optional property to the bundles definition in the manifest.json so it could be passed to the kernel to instantiate a different set of bundles like the environment now. But this won't work for recipes we don't control like the security-bundle. So we don't really have a solution in mind right now. Two Applications seems not really developer-friendly and maybe not worth the effort.

Annyway, thanks for your quick response.

**Comment by Pierstoval** [comment]
> Two Applications seems not really developer-friendly and maybe not worth the effort.

So why so many developers are making conferences about "how they migrate to micro-services"? 😉 

I would also suggest using two different apps, and sharing code via private composer packages/repos, or with plain symlinks.

You can also use a single-kernel app and use different kernel environments if you need, and define bundles only for a specific environment (this would actually be more Flex-friendly)

**Comment by danrot** [comment]
@Pierstoval if you think about a product that should be easy to use and install you can imagine that micro-services add a huge cognitive overhead, so I also don't think that's something beneficial in terms of DX (IMO the main reason for symfony-flex).

But maybe we can put the question another way: Will symfony-flex provide some extension points, which would enable to build an easier solution for the multi-kernel environment?

@fabpot Since you've closed the issue, can we interpret that as you do not have any plans to support multi-kernel setups in symfony-flex at all?

@chirimoya Another solution might be to see that a little bit more relaxed and rely on a single kernel, and we provide a guide explaining how to build two different apps for the administration and the website sharing the same database, in case somebody feels that this is necessary? Would probably make our code easier and maybe even solve some other DX issues we have.

E.g. having two different consoles is not optimal, since some commands have to be executed in both of them and people happen to forget one of them, leading to confusing situations. In a single kernel setup that would not be the case anymore, and if somebody decides to have a multiple app setup for performance reason it might be more clear that it has to be executed in both applications.

All I'm saying is that we should maybe think about enforcing our multi-kernel setup again. I think the most critical point for having a multi-kernel setup is that we don't want a session to be started on the website app, but maybe there's another solution for that? What if we keep a `CONTEXT` environment variable, based on which our `SecurityBundle` is loading a different configuration? One of these configurations could then disable the firewall and all other services that are starting a session. Resp. I just found a page in the [Symfony documentation](http://symfony.com/doc/current/session/avoid_session_start.html), which explains how to avoid starting a session for anonymous users, that also sounds like a reasonable solution to me.

**Comment by stof** [comment]
@danrot as the console Application depends on the kernel to find commands, having some commands running on both kernels would be a nightmare. For commands needing to be executed on both kernels, I think a better solution is to use the Makefile to put a task in it executing both commands.
