### ISSUE TITLE
Possibility to skip recipes or avoid the use of flex

### ISSUE THREAD

**Issue by luishdez** [symfony/flex#218]
I saw https://github.com/symfony/flex/issues/181 that tells something similar

The case is, I prepare a project with flex all good. Like some official repos and some from contrib too.

```sh
composer create-project "symfony/skeleton:^3.3" test
cd test
composer req alcaeus/mongo-php-adapter
composer req annotations
composer req doctrine/mongodb-odm-bundle
```

Then I want alice for fixtures that works fine with mongo, but the recipe defines the ORM so it fails, but now I can't install it as usually just from packagist because of flex is installed.

```sh
composer req hautelook/alice-bundle
```

`
… has   a dependency on a non-existent service "doctrine".                           
Installation failed, reverting ./composer.json to its original content
`

The thing is if someone set something that doesn't match your config in the recipes you're force to use Flex or not at all ?  Wouldn't be possible something like
`composer req --skip-flex …`

Maybe I'm missing something.

**Comment by Pierstoval** [comment]
There should be an error somewhere. Flex is not the problem here.

`DoctrineMongoDBBundle` does not define the `doctrine` service but `doctrine_mongodb` instead, and AliceBundle's default config does not use the ODM but the ORM (see [the recipe here](https://github.com/symfony/recipes-contrib/blob/master/hautelook/alice-bundle/1.4/config/packages/dev/hautelook_alice.yaml)).

To fix this, run `composer req hautelook/alice-bundle --no-scripts`, then `cache:clear` & `assets:install` won't be executed and everything will work like a charm after you update AliceBundle's config file with ODM.

**Comment by luishdez** [comment]
Yeah I know. Thats the problem I don't want to use `doctrine` service "orm" but mongo, but the Flex recipe is defined with orm, that why I did ask about a way to skit the execution of the recipe.

**Comment by Pierstoval** [comment]
Yeah, you don't, but the flex recipe is in `recipe-contrib` and the providers decided to configure the orm by default.

As said, if you don't want it, just run with `--no-scripts`, and when you have updated your config to use the ODM instead of the ORM, run `composer run auto-scripts` to run what `--no-scripts` prevented to run.

There is currently no solution.

Flex is smart, but its goal is not to configure based on already installed packages. This could however be done directly in `hautelook/alice-bundle` by the way, with a compiler pass, and maybe an option enabling auto-detection. But this needs a contribution on the bundle :wink:

**Comment by luishdez** [comment]
Sorry @Pierstoval  I didn't get that `--no-scripts` is what I was looking for to avoid the execution of recipes.

**Comment by Pierstoval** [comment]
You're misunderstanding: `--no-scripts` will simply not execute the `post-install-cmd` or `post-update-cmd` scripts (which are both using `auto-scripts` customized by Flex recipes).

Recipes will still be executed even with `--no-scripts`. But scripts won't, and that's why the whole `composer req` command is failing.

But I think #216 will completely fix this :wink:

**Comment by luishdez** [comment]
Ok I see now… then I did understand it right at first place. If you use flex , you will use with all the consequences… There is no option to avoid that the config file is copied… But you can avoid the reverting of the installation with --no-scripts. 

I hope that in future versions flex becomes more "flexible" 

Thanks for clarifying the things!

**Comment by fabpot** [comment]
Two things:

 * You are always free to remove/tweak generated files, they are yours (if you remove a file, Flex won't recreate it);

 * The failure in your case is something we are working on and should hopefully be fixed soon.

**Comment by enumag** [comment]
> if you remove a file, Flex won't recreate it

@fabpot Sadly that's not always the case. We had numerous issues where one member added some bundle, changed or removed some generated flex files but when another member checked out the commit flex tried to apply the changes again.

**Comment by xabbuh** [comment]
@enumag Are you able to provide some steps to reproduce? Are sure that's still happening after the introduction of the `symfony.lock` file?

**Comment by enumag** [comment]
@xabbuh Also how do I generate the file? It doesn't exist on my PC and when I run `composer update` it creates the `symfony.lock` file but it only contains `[]` which is not correct.

**Comment by Pierstoval** [comment]
@enumag the `symfony.lock` file is here to save which recipes have been executed and should not be applied again when installing your project. It must be added to your VCS.

To generate the file, you can save all your project in your git branch, remove `vendor` and run `composer install` again. As there is no `symfony.lock` file, recipes will be applied and some files you removed might be created again. Once the installation is done, you can remove the added files you don't want anymore, and add `symfony.lock` to Git and it should fix all your problems

**Comment by Pierstoval** [comment]
> The unpredictability of when and how the file is changed was the reason I added it to .gitignore by the way.

This lockfile is created when a package is installed. For all packages, it will store the installed version. This is similar to `composer.lock`, but if a recipe is installed, its metadata will also be present. And Flex will know not to install the recipe again if it's found during a `composer install`.

**Comment by enumag** [comment]
@Pierstoval Thanks for the explanation. This is exactly the kind of information I'd expect to read in flex documentation.

**Comment by hipio** [comment]
@enumag A short explanation of the `symfony.lock`-file can be found over at https://symfony.com/doc/current/setup/flex.html (which was added in [October last year](https://github.com/symfony/symfony-docs/commit/6d0d8f5b881591f4f9597e17920a53af1422e903)).

> Flex keeps tracks of which recipes it installed in a `symfony.lock` file that must be committed in your code repository.

It is rather short so if it doesn't cover everything you need to know, feel free to create an issue/PR!  :smiley:
