### ISSUE TITLE
Symfony repository as flex recipe repository

### ISSUE THREAD

**Issue by drgomesp** [symfony/flex#294]
I'm not sure about this, but I think there's a mistake here. On the image below, where it says `config.json`, I think it was supposed to be `manifest.json`?

Also, it's very confusing. Where is that `projects` key supposed to be added? In the recipes repository or the actual project repository (the one using the recipes)?

![screen shot 2018-01-15 at 12 43 45 pm](https://user-images.githubusercontent.com/696982/34933822-cabec450-f9f1-11e7-9e0d-56ec5512dfe4.png)

**Comment by Pierstoval** [comment]
The `config.json` is supposed to be in your Flex repository, not your project.

**Comment by remialvado** [comment]
I'm also trying to use Flex to configure our private repositories. I've got a bunch of Symfony applications (around 20) that depends on a `wizbii/mongo` package (which also depends on some other private packages but that's another story) that require some environment variables. I'd love to use Flex to add those environment variables to `.env` and `.env.dist` files and I've tried to configure a "private" flex recipe repository.

I've configured one (https://github.com/wizbii/wizbii-symfony-recipes) and registrered it on symfony.sh as a private repo (even if it's actually a public one for the moment) but it does not do anything when I install this dependency : 

```composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)

Prefetching 2 packages 🎵
  - Downloading     
    Authentication required (infra-satis.wizbii.com):
      Username: 
      Password: 
 (100%)         

Package operations: 4 installs, 0 updates, 0 removals
  - Installing wizbii/serializer (1.0.0): Downloading (connecting...)    Failed to download wizbii/serializer from dist: Invalid credentials for 'https://infra-satis.wizbii.com/dist/wizbii-serializer-1.0.0-050baa.tar', aborting.
    Now trying to download from source
  - Installing wizbii/serializer (1.0.0): Cloning 4c1c3374ef from cache

  - Installing symfony/stopwatch (v4.0.3): Loading from cache
  - Installing mongodb/mongodb (1.1.2): Loading from cache
  - Installing wizbii/mongo (0.0.2): Downloading (connecting...)    Failed to download wizbii/mongo from dist: Invalid credentials for 'https://infra-satis.wizbii.com/dist/wizbii-mongo-0.0.2-ff9e6b.tar', aborting.
    Now trying to download from source
  - Installing wizbii/mongo (0.0.2): Cloning fa012bbe95 from cache
Writing lock file
Generating autoload files
Symfony operations: 1 recipe (e875501d28232ed7c02a5129876a359e)
  - Configuring wizbii/mongo (>=0.0.2): From auto-generated recipe
Executing script cache:clear [OK]
Executing script assets:install --symlink --relative public [OK]

Some files may have been created or updated to configure your new packages.
Please review, edit and commit them: these files are yours.```

`wizbii/mongo` is indeed installed and add in bundles.php since it has `symfony-bundle` type but my recipe is not installed. Any idea? I can't find any clear documentation about this feature for the moment :(
Thanks!

**Comment by xabbuh** [comment]
Is `01C41MVD4AJ4BTB1BDV6342HCH` the value of the `extra.symfony.id` option in the `composer.json` file of the project where you are installing the package?

**Comment by remialvado** [comment]
Yes, it is : 
```
MacBook-Pro-de-Remi-2:consent remi$ composer config extra.symfony.id
01C41MVD4AJ4BTB1BDV6342HCH
```

**Comment by Leggy7** [comment]
I'd like to pick up this old issue because I can't find a clear way to deal with this.

I have a private repository on bitbucket.org and I created a recipe for it on a private github repository.
I have my package repo on bitbucket called `my_vendor/my_package` and the recipe repo has a dir structure like `my_vendor/my_package/version/`

To be honest it is not clear to me how package repo and its related recipe are linked so I supposed the magic was somewhere between package name and recipe dir structure and everything should've been handled after my recipe repository was registered with the flex server github app. Last thing I did was to give an id in my package repo `composer.json` at `extra.symfony.id` and create a `config.json` file in my recipe repository (inside the rootdir) with allowed projects ids in the form of 
`"project_id": "totally random stuff"`


When I run composer update the recipe is not downloaded and I have several problems identifying a way to solve the puzzle.

Could anyone please enlight me on the right procedure?

**Comment by gesof** [comment]
I'm in the same boat. The development goes forward on too fast and the documentation is far behind resulting in helpless users. 8 months later and you did not get a clear answer and no article seems to be published to clarify how to use this feature step-by-step.

**Comment by simon-schubert** [comment]
I'd like to bring up the discussion here again, because i played around with the private symfony-flex-server on github and figured out couple of things, but still have questions. This is what worked for me:
* create a new recipe-repository on github
* activate symfony-flex-server as a github app (repository-settings > integration & services) for this repository (http://fabien.potencier.org/symfony4-flex-private-repositories.html)
* add a recipe according to documentation in symfony/recipes readme
* create a pull request (!important to get a test environment)
* check the environment created by the symfony-flex-server 
* add SYMFONY_ENDPOINT environment variable (real env var, not in .env) for the env where the project runs which will require the bundle
* run `composer require my-vendor/my-bundle`

As long as i have set the SYMFONY_ENDPOINT for any PR i can use my private recipe-repository's recipe for flex. -> testing works
What i can't figure out is: How can i use my private recipe-repository for production, when not just testing the PR?

**Comment by simon-schubert** [comment]
I finally found out by myself: it's a matter of time. After merging a PR approved by the symfony-flex-server it seems to me, that it takes a while (at least if you have newly registered your private recipe-repository on github). After some time, my private recipes where available via flex calling the official api https://flex.symfony.com and my private recipe got executed same as official or contrib ones.

**Comment by nicolas-grekas** [comment]
Closing as there is no bug here. Missing doc maybe. Please consider contributing to symfony-docs.
