### ISSUE TITLE
"mirrors" is not a valid alias

### ISSUE THREAD

**Issue by erichard** [symfony/flex#394]
When using [packagist.com](https://packagist.com) we need to launch the command `composer update mirrors` but it fail with the error `"mirrors" is not a valid alias`.

I only get this since I'm using flex.

**Comment by stof** [comment]
if you want to perform a partial update matching no installed packages, use `composer update --lock` rather than passing a fake package name.

**Comment by erichard** [comment]
So you think it's a problem in the packagist.com documentation ? I've always think this command do something special but maybe not :-) 

I have submitted the problem to the packagist.com team.

**Comment by stof** [comment]
Well, without using Flex, `composer update mirrors` will work (but displaying a warning about `mirrors` not being one of your requirements.
Flex provides a system of package aliases, relying on the fact that anything without a `/` in them cannot be a valid package name on packagist.org (or anything else running the same validation rules) and so tries to resolve them against the Flex aliases. This indeed breaks the case where you used it only as a fake package name to whitelist nothing. But composer has this `--lock` option for this purpose since years and so we decided that it was acceptable (and much better DX when the non-matching alias is because you made a typo when writing the alias).

**Comment by stof** [comment]
@nicolas-grekas a way we could improve this on the Flex side is detecting that this error happened while running `composer update` (rather than `require` or `remove`) and suggest using `--lock` instead if they intended to regenerate the lock file only.

**Comment by Seldaek** [comment]
composer update mirrors is a valid way to do this, much like composer update lock is, it doesn't print a warning. If flex can ignore those invalid aliases that would be great. --lock is just an alias to do `composer update lock` internally.

**Comment by stof** [comment]
@Seldaek but which invalid aliases should it ignore ?

**Comment by Seldaek** [comment]
`mirrors` and `lock` as they have a special meaning to composer.

**Comment by stof** [comment]
OK, then we should forbid using these 3 names as aliases in Flex (will require updating the validation rules in the Flex server), and avoid resolving them as alias /cc @nicolas-grekas @fabpot

**Comment by nicolas-grekas** [comment]
See #395

**Comment by fabpot** [comment]
I've just added the new validation rule in the Flex server (and added the rule here: symfony/recipes@c0124f7). Test PR is here: https://symfony.sh/r/github.com/symfony/recipes/444

**Comment by nicolas-grekas** [comment]
I'd suggest to allow "lock", as the outcome is not an issue: when symfony/lock is not installed, this still works:
![image](https://user-images.githubusercontent.com/243674/43273254-452a2f26-90fc-11e8-94f2-af4a1696ebfe.png)

And `composer require lock` still installs symfony/lock

**Comment by stof** [comment]
but `composer update lock` would whitelist the symfony/lock package for the update when Flex is installed, differing from being the same than `composer update --lock`.

**Comment by nicolas-grekas** [comment]
yes, and that's fine to me, we take over the "lock" alias
