### ISSUE TITLE
New command upgrading existing app to Flex

### ISSUE THREAD

**Issue by maidmaid** [symfony/flex#407]
What about a `flex:upgrade` command which would set up the new directory structure as described in the [doc](https://symfony.com/doc/current/setup/flex.html#upgrading-existing-applications-to-flex) and as realized by @javiereguiluz in https://github.com/symfony/demo/pull/617?

According to this doc:

> There's no automatic tool to make this upgrade, so you must follow these manual steps

Isn't it supposed that a such automatic tool will soon be created ? :thinking:

**Comment by Pierstoval** [comment]
This is not possible to "just" update the structure. Every project has so many different forms of configuration and structure that doing everything manually is the best option anyway.

And changing the structure of a project can be a BC-break if the project is using `kernel.root_dir` sometimes, because this parameter refers to the `app` dir in SF2/3 and to the `src` dir in SF4. And plenty other issues that I don't think an upgrader could support :confused:

**Comment by nicolas-grekas** [comment]
There is no bullet silver here, but https://github.com/symfony/flex/pull/439 should help.
