### ISSUE TITLE
[Question] Custom Installers & Plugin Capabilities

### ISSUE THREAD

**Issue by maxhelias** [symfony/flex#545]
On the documentation of Composer, they talk about two concepts that are quite interesting, the custom installers distributed in a plugin and the capabilities of a plugin.

- https://getcomposer.org/doc/articles/custom-installers.md

- https://getcomposer.org/doc/articles/plugins.md#plugin-capabilities

For the command part, the documentation does not mention the construct parameters that are passed to the provider and that would make the integration possible with Flex to inject command dependencies (this could also be useful for issue #518) .
https://github.com/composer/composer/blob/e022c073706769d0486de96de0f98719cd9950b5/src/Composer/Plugin/PluginManager.php#L375

Is there a particular reason to not use these concepts for Flex ? If we can use them, with a little help, I could study the question more seriously and work on it 😃

**Comment by nicolas-grekas** [comment]
Flex is compatible with Composer 1.0, which doesn't have plugin capabilities.
About installers, why would it be useful?

**Comment by stof** [comment]
the custom installer concept is not used by Flex because Flex does not customize the installation layer at all. It customizes the downloader (to perform parallel downloading when possible, until Composer 2 has it in core), the loading of metadata in repositories, customizes the default options of some commands (disabling display of suggestions for instance), registers some extra commands and reacts to some of the events (using the standard composer way for plugin).

The CommandProvider capability would indeed be a way to implement the `registers some extra commands` part in a cleaner way in newer composer versions. But the other stuff would still require the logic we have today (command providers cannot replace built-in composer commands). And this would be incompatible with older composer versions (with no easy way to provide a good handling of that case).

**Comment by maxhelias** [comment]
Thanks for the information, it's now much clearer
