### ISSUE TITLE
Unpack all packages?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/flex#563]
Usually I don't care about unpacking packs ... but I was playing with this feature and tried to run this command:

```bash
$ composer unpack

  [Symfony\Component\Console\Exception\RuntimeException]
  Not enough arguments (missing: "packages").
```

For those of you who usually unpack packages, what do you think about adding  support to unpack all packs at once running the `composer unpack` command without arguments? Would that be useful ... or is not a common need to unpack everything? Thanks.

**Comment by Pierstoval** [comment]
I would even add a list of packs that will be unpacked and the dependencies that will be resolved, and add a prompt to ask confirmation to do it 👍 

And I would even go further: unpack all packs _by default_ when requiring them.
Like `composer require symfony/orm-pack` would automatically resolve to `composer require doctrine/orm doctrine/doctrine-bundle doctrine/doctrine-migrations-bundle` instead.

Packs kinda "hide" installed dependencies, and they are even considered as "transient dependencies" in the end, because you don't use what's in the pack, you only use what's _provided_ by the pack (that might change one day).

Like, what if one day `symfony/debug-pack` doesn't provide Monolog anymore? Or if `symfony/serializer-pack` stops providing `symfony/property-access`?
A `composer update` would remove these, and that's not really a good idea IMO.

**Comment by DanielBadura** [comment]
I only use packs to install all the things i need. Im unpacking them after that instantly. I don't like the idea of having hidden dependencies in my projects. I like the idea from @Pierstoval to unpack by default. But `composer unpack` which would unpack everything would be fine for my use case. Or maybe as an option: `composer unpack --all` just to be explicit?

I would appreciate one of these solution that i don't need to unpack everything manually especially because some packs require packs (amqp-pack requires serializer-pack as an example).

Thumbs up from me 👍

**Comment by maxhelias** [comment]
I agree to review the operation of the packs as well.

@Pierstoval, we currently have the case with the orm-pack (https://github.com/symfony/orm-pack/blob/v1.0.7/composer.json) which bump doctrine-bundle to version 2 and there's a lot of open issue associated with it because many projects have been broken by this transparency :/

**Comment by nicolas-grekas** [comment]
I'm not sure that unpacking should be provided as a helper, but listing all existing packs as a suggestion when no packs are provided on the command line could be nice.

`$this->getComposer()->getRepositoryManager()->getLocalRepository()` should give access to the list of installed packages. Iterating over them to find those with type 'symfony-pack' could be a starting idea to implement this.

PR welcome, help wanted.

**Comment by nicolas-grekas** [comment]
Now that unpacking happens by default, I don't think this will get any tracking.
I'm therefor closing. PR welcome if someone wants to work on it.
