### ISSUE TITLE
[RFC] API Endpoint to fetch historic recipe by sha? (for proper removing & better update)

### ISSUE THREAD

**Issue by weaverryan** [symfony/flex#593]
Hi!

This can probably only be answered by Fabien. Is it feasible for the Flex API to support fetching an *old* version of a recipe? For example, suppose we're talking about `twig/extensions`. Would it be possible to ask for the `c986e32` sha of the 1.0 version of the recipe (which would be one commit *before* HEAD - https://github.com/symfony/recipes/commits/master/twig/extensions/1.0 )?

*If* we could do this, it would allow us to do two more things slightly more accurately:

1) On package removal, we could remove using the same version of a recipe as the user originally had installed. Minor - but better.

2) On package update, we could remove using the original recipe first and THEN upgrade to the latest. That would fix the problem where a file/parameter that was added in the OLD recipe is NOT added in the new recipe. Currently, that file/parameters is NOT removed. But if we were able to remove the original recipe, it WOULD remove that old file/parameter.

So, is that possible to add to the API? 

Thank you :).

**Comment by nicolas-grekas** [comment]
Just fetching recipes by tree-hash wouldn't be enough: we'd need to resolve symlinks also. But I don't think symlinks from a tree-hash can resolve to the target corresponding to the hash. Because a tree hash doesn't snapshot the target, we cannot know the state of the target.

We need to resolve this before.

One way would be to forbid symlinks - and rewrite the history of this repo to resolve them all also.
Alternatively, we could have a bot create a shadow git history with resolved symlinks, and the tree-hash would map to this shadow repo, instead of the main

**Comment by maxhelias** [comment]
In fact, I think we can do it without changing the endpoint.
As we save the files added by the recipe in the .lock, we should be able to delete them and install those of the new recipe. And for the other cases, the hash is sufficient to retrieve the configuration of the manifest.

I may be wrong or forget some cases ?

**Comment by nicolas-grekas** [comment]
#803 should provide all the answers to this question \o/
