### ISSUE TITLE
symfony version restriction exception

### ISSUE THREAD

**Issue by Nemo64** [symfony/flex#619]
I want to install a symfony package (specifically the [amazon-mailer](https://github.com/symfony/amazon-mailer)) in a newer version than every other package.

However, my project contains this version contstaint
```
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "4.4.*"
        }
    }
```

This is evaluated here: https://github.com/symfony/flex/blob/v1.6.3/src/Cache.php#L80 which effectifly prevents the installation of newer packages, which is fine for all packages except for the 1 that I want to install in a newer version.

My current workaround is to add the beta version to the global restriction. This works as long as `5.1` is in beta but if it becomes stable, I won't be able to have this version missmatch without accidentally installing other symfony components at a newer version.

```diff
"extra": {
    "symfony": {
        "allow-contrib": false,
-       "require": "4.4.*"
+       "require": "4.4.*||v5.1.0-BETA1"
    }
}
```

I'd like to add exceptions to this constraint, something like:
```diff
"extra": {
    "symfony": {
        "allow-contrib": false,
        "require": "4.4.*"
+       "ignore-versions-of": ["symfony/amazon-mailer"]
    }
}
```

Or better yet, ignore the version of all packages that are explicitly installed which would allow the simple `composer require symfony/amazon-mailer:v5.1.0-BETA1` without having to do anything.

**Comment by nicolas-grekas** [comment]
You can achieve this by forcing all other components to 4.4.* while allowing 4.4|5.1 in extra.symfony.require.

Doing what you propose would mean providing a simpler way to achieve something that is already possible (a bit painful I agree). I don't think this is worth the complexity and the maintenance effort this will require in flex. Also, this could lead to having ppl less likely to upgrade.

:-1: on my side with this reasoning.

**Comment by Nemo64** [comment]
Yeah, I kind of see it.
I should be using symfony 5.1 if I want any feature of it since it'll make testing for you a lot simpler.

**Comment by nicolas-grekas** [comment]
Note that `extra.symfony.require: 5.0.*` doesn't apply to components that are new to 5.1. Eg. you can install `symfony/amazon-sqs-messenger` which only exists since 5.1.

**Comment by Nemo64** [comment]
I could kiss you right now... I was planning on using sqs with the symfony messenger and I wasn't aware that there is an official implementation for 5.1 in the works. That is awesome.

I'm closing this issue as I see the contra argument.

**Comment by c33s** [comment]
please reopen, the problem is still there. 

yes it's true that requiring a newer package which simple does not exist in an older version works but it is really a bad DX if i can't simply install a specific higher package which has no conflicts with the current lts version. in my case i would like to install a newer workflow component in 4.4 lts project.

`"ignore-versions-of"` would be really cool or if the following code works (sorry for the yaml, i use composer.yaml):

`composer.yaml`:
```yaml
name: c33s/symfony-require-test
type: project
require:
    symfony/workflow: "5.5.1 as 4.4.10"
config:
    preferred-install: { '*': dist }
conflict:
    symfony/symfony: '*'
extra:
    symfony:
        require: '4.4.*'
```
`symfony/workflow: "5.5.1 as 4.4.10"` with this code snippet composer allows to change the version number of a component but flex annuls this composer feature by filtering the version list "before" composer "converts/changes" the version number.

> You can achieve this by forcing all other components to 4.4.* while allowing 4.4|5.1 in extra.symfony.require.
> Doing what you propose would mean providing a simpler way to achieve something that is already possible (a bit painful I agree).

the key here is "a bit painful" which says bad DX (at least for me).  also we have quite a lot of "magic" in here. where the list come from? which list is taken, require (no it's the replaces list)? why does my composer feature of version aliasing doesn't work any more?
this leads to confusion and to questions like that (also see the comments):  https://stackoverflow.com/questions/59166939/how-composer-extra-symfony-require-restriction-is-enforced 

> don't think this is worth the complexity and the maintenance effort this will require in flex.

it's a little bit like, implementing a download csv/xls is too much maintainance effort, let the users copy and paste the values from the website to excel or not having a `string_ends_with()` function in php core.

> Also, this could lead to having ppl less likely to upgrade.

this makes me a little bit sad. shouldn't the goal be that ppl don't have to upgrade all the time? i love symfony for having a more strict semver policy and that symfony has a lts version. i want to upgrade without effort, so i love patch releases, they simply work. so i want to stick with lts until the next lts version but why should this block me from using a 5.x component if there is no conflict and if the component has a feature i need? why is the current solution to force the user to

-  use a full non-lts version
- fork the component to give it a different name to add it to the project
- drop the flex feature to use `extra.symfony.require` and having to readd all the version numbers to symfony components
- stay with the older version and code without the features of the new version

as far as i understand, symfony flex has a version filter, so it takes the list of all matching symfony/symfony components and filters all versions contained by for example `4.4`

is it realls so much maintainance effort to add one step the filter, where after the list is fetched the list is filtered by the exclusions and the "real" filter is only applied on the resulting package list?

give users/developers control, it is possible that they can handle it :)
