### ISSUE TITLE
Library composer/ca-bundle handled as Symfony bundle - wrong auto-generated recipe

### ISSUE THREAD

**Issue by RicoFactset** [symfony/flex#622]
Hi,

please see comment from https://github.com/Seldaek in [](https://github.com/composer/ca-bundle/issues/56) which relates to [](https://github.com/symfony/flex/blob/89999fdaad52cab14637709f2d2ce25835a051e6/src/SymfonyBundle.php#L78). Seems additional checks are required.

Type of ca-bundle is "library" and not "symfony-bundle"
[](https://github.com/composer/ca-bundle/blob/master/composer.json#L4)

Thanks
Rico

**Comment by andrew-demb** [comment]
Flex now try to auto discover bundle classes not only for `symfony-bundle` packages.

Ref https://github.com/symfony/flex/pull/612

**Comment by sstok** [comment]
FYI. If you need something to keep your (use an) CA bundle up-to-date have a look at https://github.com/paragonie/certainty/ 👍

**Comment by drupol** [comment]
In the meantime, to fix the issue, constraint `symfony/flex` version to `1.6.2`.

**Comment by weaverryan** [comment]
I can confirm this. To repeat:

```
composer create-project symfony/skeleton ca-bundle-recipe-bug
cd cd ca-bundle-recipe-bug
composer require composer/ca-bundle
```

And then the error:

<img width="1279" alt="Screen Shot 2020-05-27 at 9 48 30 AM" src="https://user-images.githubusercontent.com/121003/83028327-42896980-9fff-11ea-9391-831380b48efe.png">


Ping @SerheyDolgushev do you have any ideas on how this might be fixed?

Btw - this is affecting `blackfire/php-sdk`, as it requires `composer/ca-bundle`.

**Comment by stof** [comment]
The new detection of bundle classes in any package type might require adding a validation that the detected class is actually a class implementing the Symfony BundleInterface, and not a random class with a name ending with `Bundle`.

Making the assumption that a class ending with `Bundle` in a `symfony-bundle` package is actually a Symfony bundle could be considered OK. But removing the restriction on the package type makes it much harder to justify this.

If we decide we don't want to implement such validation because broken cases would be very few, we could probably solve it by adding an explicit recipe for `composer/ca-bundle` forcing to define an empty array of bundle classes (which will disable the automatic detection).

**Comment by fabpot** [comment]
See #627

**Comment by fabpot** [comment]
I've just tagged 1.7.1 with the fix.
