### ISSUE TITLE
symfony/flex 1.7 and symfony 4.3.*

### ISSUE THREAD

**Issue by kevin-lot** [symfony/flex#626]
dump-env command from DumpEnvCommand doesn't work in version 1.7.0 and Symfony 4.3.11.

Example:
composer dump-env prod

Issue is here : https://github.com/symfony/flex/blob/d606fabffa3547a61632bcf3b3bb677e79475449/src/Command/DumpEnvCommand.php#L76

**DotEnv class is not found** and message alerts to install symfony/dotenv even if the package is already installed.

**Comment by stof** [comment]
Given that Symfony 4.3 is EOL, I don't think this is worth working on.

**Comment by denisschafer** [comment]
Can you please add a require symfony minimum version 4.4 in the composer.json from version 1.7 so that we don't get a breaking change by mistake?

**Comment by nicolas-grekas** [comment]
There's no breaking change here - at least none we have control over.
I just had a look and I don't understand what the issue is.

I only have a symptom:
Patching the vendor/composer/installed.json this way make composer able to autoload the class:
```diff
         "name": "symfony/dotenv",
         "version": "v4.3.11",
-        "version_normalized": "4.3.11.0",
+        "version_normalized": "4.4.11.0",
```

Why? Zero idea. Please investigate if you can.
/cc @Seldaek in case this makes sense to you.

**Comment by Seldaek** [comment]
@nicolas-grekas you mean patching the version there and then running composer install or something? If just patching this then I doubt it would fix anything as installed.json is not loaded at runtime at all. But in any case this doesn't seem like a familiar issue to me sorry.

**Comment by nicolas-grekas** [comment]
@Seldaek thanks for commenting here.
Just patching and running `composer dump-env prod`, nothing in between.
Since that's a composer command, we're not in the usual autoloading stack.

@kevin-lot @denisschafer I'm sorry but you should either upgrade or investigate the cause here. Unless the issue can be reproduced with a supported version in the future, I'm not going to be able to spend more time on this.

**Comment by nicolas-grekas** [comment]
For the record, my reproducer is:
```sh
symfony new test43 --version=4.3
cd test43
composer dump-env prod
```

**Comment by denisschafer** [comment]
No pb. I totally agree that spending too much time on non-supported version is useless. We are gonna limit symfony/flex version to 1.6.* an all our symfony 4.3 project until the migration to 4.4 and 5 is completed.

**Comment by sirdiego** [comment]
We use Symfony 4.3 because of the LTS status. And we had to update symfony/flex to a current version to get Composer 2.0 support. That update broke the `composer dump-env prod` command. Is there any workaround to get it working with Symfony 4.3 and Composer 2.0?

**Comment by nicolas-grekas** [comment]
4.4 is LTS, not 4.3

**Comment by sirdiego** [comment]
Oh, I'm so sorry... We got it all mixed up. Thanks for the reply.
