### ISSUE TITLE
[Feature] Allow to override some environment variable when using `composer dump-env`.

### ISSUE THREAD

**Issue by VincentLanglet** [symfony/flex#679]
During my deployment I would like to add the current git commit SHA to my env variables.

I would have expect to run something like
```
MY_ENV_VAR=foo composer dump-env prod
```
Or
```
composer dump-env prod --option MY_ENV_VAR=foo
```

To dynamically override the value of the MY_ENV_VAR.

Does this option exists ? Wdyt about adding it ?

**Comment by nicolas-grekas** [comment]
--set FOO=bar could work. Up to give it a try?

**Comment by fabpot** [comment]
You can also use a valid shell command in a .env file.

**Comment by VincentLanglet** [comment]
> --set FOO=bar could work. Up to give it a try?

I get 
```
[Symfony\Component\Console\Exception\RuntimeException]  
  The "--set" option does not exist. 
```

You mean trying to implement it @nicolas-grekas ?

**Comment by nicolas-grekas** [comment]
Yes :)

**Comment by Toflar** [comment]
Just a quick note: I also think the logic should be part of the `DotEnv` component itself. So that we can call `$dotEnv->dumpToFile($path....)` or whatever. Right now, you cannot build your own `dump-env` command without copying loads of stuff from Flex. But you might want to use the component outside of Flex which is why it was designed as a component in the first place, right? :-)

**Comment by nicolas-grekas** [comment]
This can be achieved by dumping the extra env vars in eg `.env.local` if I'm not wrong.
There's also this effort to move that command to Symfony: https://github.com/symfony/symfony/pull/42610
I'm closing therefor.
