### ISSUE TITLE
Overwrite existing files

### ISSUE THREAD

**Issue by Anyone1990** [symfony/flex#731]
Is it possible with a recipe to overwrite a file? I need to create a recipe in which I need to replace an existing file (webpack.config.js which was created previously due to webpack encore bundle)  and I don't want to either use remove commands or sed command for replacing string manually since these are os specific commands.

Best regards

**Comment by dbrumann** [comment]
No, overwriting files is currently not possible. Any file created by Flex belongs to users, which is why you should check the diff before committing changes done by a recipe. That means, once there is a file Flex does not know whether it was the original file, whether it was modified or whether the user already had their own file (and what they changed). There is only a few places (e.g. .env or bundle.php) where the simple structure and helpful placeholders support this. For complex files like configs or even code, this would be too much work.

You can however create your own bundle with your config and then install it before (or instead of) the encore-bundle. Otherwise you will need to do these steps manually or via a command/script after the installation.

**Comment by Anyone1990** [comment]
Thanks for your explanation. The problem here is, that I also need to "purge" the assets directory that is provided by webpack encore bundle. I guess that for this scenario I don't really have much options instead of doing it manually. Thank you!
