### ISSUE TITLE
Overwrite services.yaml

### ISSUE THREAD

**Issue by Anyone1990** [symfony/flex#732]
I am developing a bundle and in order to keep the installation as simple as possible it would be great if there would be an option to append new service definitions to the symfony application by installing the recipe. Is there anything like this planned?

I know that a bundle can provide its own services.yaml, but apparently referenced classes in the App\ namespaces  in the bundles services.yaml are not considered while the DI container is built. I guess it is because of the services.yaml in app config directory provided by symfony which overwrites these definitions immediately.

Best regards

**Comment by dbrumann** [comment]
The default `services.yaml` will load all classes under `App\` (see: [framework-bundle recipe](https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/4.4/config/services.yaml#L16-L22)). If your bundle provides files that can not be autowired (e.g. because they require parameters) you should likely provide a configuration for it instead and load these services via your bundle.

Generally speaking, your bundle should only put code in `src/` that will later belong to users, i.e. that they should modify. As an example [AppFixtures.php from doctrine/doctrine-fixtures-bundle](https://github.com/symfony/recipes/blob/master/doctrine/doctrine-fixtures-bundle/3.0/src/DataFixtures/AppFixtures.php) should be modified by users and contain their app fixtures for their app code, which is why it is in src/. All the code for doctrine-fixtures to run the migration (e.g. the fixture-load-command) is part of the library/bundle instead and not stored in src/.

**Comment by Anyone1990** [comment]
Thanks for your answer. I don't know exactly if I understood your explanation correclty. My scenario is:

I have my own bundle which is configured to have  services which are tagged with a custom tag provided by the bundle. Let's call this tag 'mybundle.xyz'. The bundle itself provides a set of pre defined xyz classes that are tagged with the previous mentioned tag. I created a CompilerPass which looks up for all classes that are tagged with this tag (via findAndSortTaggedServices). However, the idea of the bundle (or more specifically the CompilerPass) is to also consider all classes in the App\XYZ namespace as 'mybundle.xyz' tag. As an example:

`App\XYZ\:
        resource: '../src/XYZ'
        public: true
        tags:
            - { name: 'mybundle.xyz', priority: 0 }`
  
It works with the above configuration placed in app services.yaml. I tried to move this configuration to the bundle itself but it doesn't work. This seems to be because the CompilerPass does not recognize them as tagged with 'mybundle.xyz' since, I guess, this definition is overwritten with the app services.yaml. 

If I understood you correctly, I should instead try to configure this with a custom bundle configuration which stores the app path in which the xyz-classes reside and add them manually to the pass, right?

**Comment by dbrumann** [comment]
I suggest taking this to [one of the support channels, e.g. #support in Slack or StackOverflow](https://symfony.com/community) instead.

> If I understood you correctly, I should instead try to configure this with a custom bundle configuration which stores the app path in which the xyz-classes reside and add them manually to the pass, right?

Yes, kind of. Instead of going by path you should probably check for a specific type, but in any case it's a job for your bundle and not for flex/your recipe. For example this is [how Symfony's FrameworkBundle collects Commands](https://github.com/symfony/symfony/blob/5.x/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L457-L458) for registration.

**Comment by Anyone1990** [comment]
Thank you very much for your help, this is indeed a way better approach then. I guess I can close this issue.
