### ISSUE TITLE
[RFC] Allow packages to bundle their respective recipes as source code instead of forcing a separate repo

### ISSUE THREAD

**Issue by gggeek** [symfony/flex#745]
Wouldn't it be easier both to maintain and discover recipes within the original source code, than keeping them on a separate repo/server?
Imho separate recipes should only be used for packages which are abandoned or for which the original author is against the usage of Flex...

**Comment by icanhazstring** [comment]
Actually, I was looking for this as well.
Since `symfony/flex` only checks for `"type": "symfony-bundle"` this will give developers the ability to ship the recipe with the code. This is especially useful for proprietary bundle development.

For the requirements of a package to have a recipe the following criteria should be met:
- The `type` of the package is `symfony-bundle`
- A `recipe` folder must be present in the root path of the package
- All other requirements for symfony/flex must be met (like an existing `manifest.json`)

As for the priority I could think of that
1. If `<package>/recipe/manifest.json` is present use this
2. Fallback to `github.com/symfony/recipe` or `symfony/recipes-contrib`

**Comment by nicolas-grekas** [comment]
See https://github.com/symfony/flex/pull/753#issuecomment-924109963
