### ISSUE TITLE
Add Releases / notes

### ISSUE THREAD

**Issue by mbrodala** [symfony/flex#824]
It would be very useful if each new Flex release is accompanied with a proper Github release. Currently these do not seem to be maintained that much: https://github.com/symfony/flex/releases

![image](https://user-images.githubusercontent.com/5037116/138257665-fc7e3bfa-751a-44bf-9e72-b09fc031e45d.png)

One benefit for me personally would be that I can see the release notes when [Renovate](https://www.whitesourcesoftware.com/free-developer-tools/renovate/) suggests an update for Flex.

Since release notes can be easily be autocreated from all PRs which where merged after the last release, the maintenance burden should be low.

**Comment by GPHemsley-RELX** [comment]
Indeed, other than v2.0.0, versions since v1.14.5 (including the apparent firedrill v1.14.6, all of v1.15.x, v1.16.x, and v1.17.x, and v2.0.1) have only been tagged, not released on GitHub.

In addition to the lack of associated changelogs, this means that folks who using the Watch Releases feature of GitHub are not notified of new versions.

**Comment by nicolas-grekas** [comment]
Thanks for suggesting. We'll try to improve our processes but we also want to keep things light for maintainers. That's a difficult balance.
