### ISSUE TITLE
RFC: mkdir configurator

### ISSUE THREAD

**Issue by xabbuh** [symfony/flex#86]
We already have some recipes (in both the core and the contrib repositories) that contain `.gitkeep` files that are only there to trigger the creation of directories. My question is: would it make sense to add a new `mkdir` configurator that allows to define directories that will be created by Symfony Flex and that would be removed (if empty) in the `unconfigure` step?

**Comment by chalasr** [comment]
I also think we should standardize the way directories are created by recipes.
In [this recipe](https://github.com/symfony/recipes/blob/master/lexik/jwt-authentication-bundle/2.3/Makefile#L5) I created the directory from the make task directly.

**Comment by javiereguiluz** [comment]
I'm not sure about this because:

* We already have lots of configurators; adding more will complicate learning and managing Flex.
* We shouldn't create micro-configurators: if we add a "mkdir", should we also add a "mkfile", "mksymlink", etc.?
* The `copy-from-recipe` and `copy-from-package` can already solve this and other related needs.
* I agree that creating the `. gitignore` files is a bit annoying ... but in my opinion is tolerable.

**Comment by Pierstoval** [comment]
Anyway we might propose `recipe-install-script` with scripts to be executed when the recipe is installed. This might be better than adding composer scripts, because composer scripts are executed _on each_ install, whereas these `recipe-install-script` would be executed only once.

This is nice because it would avoid having recipes that copy empty directories.

**Comment by xabbuh** [comment]
Any other opinions on this?

**Comment by fabpot** [comment]
I mostly agree with @javiereguiluz. Also, I've added a validator to check that those empty dirs are using `.gitignore` instead of `.gitkeep`.
