### ISSUE TITLE
[Feature request] Possibility to exclude recipes during update --force

### ISSUE THREAD

**Issue by fliespl** [symfony/flex#886]
Currently there is no way to exclude recipes that we know that simply will never apply in specific use case.

I.e. recipe that create Admin/Controller/Entity/Repository directories within source - we use another structure.

It would be cool if there was a way to provide list of recipes to be skipped during update/sync.

**Comment by weaverryan** [comment]
Using `recipes:update` instead of reinstalling them should help a lot. It won't avoid the problem, but you would only hit the problem if those files actually *changed* during the last time you updated them. And if they *did* change, it should be a simple git conflict that you can resolve :).

Cheers!
